spring.application.name=MainPushService
server.port=8080

#DB
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=NotificationDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=admin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate