spring.application.name=WebPushService

#vapid keys
vapid.public.key=BAIfDZp99GjLv9FyAgBB2XPX-gt7BafHz61wvAip7dQsrc_134XG5hUJ0Ao-hVDrQo8zYcELEjInf-EKjnHIamo
vapid.private.key=zl3nCx7qV_Zwk3HpMICbRpDL79WT23iSf-EaJ2fg6q4

spring.kafka.bootstrap-servers=localhost:9092

#db connection
spring.datasource.url=jdbc:sqlserver://localhost:1433;database=NotificationDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=admin
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
